[PHP]
extension_dir = "C:\Users\marjo\AppData\Local\Microsoft\WinGet\Packages\PHP.PHP.8.3_Microsoft.Winget.Source_8wekyb3d8bbwe\ext"
extension = php_pdo_sqlite.dll
extension = php_sqlite3.dll
date.timezone = UTC
display_errors = On
error_reporting = E_ALL
short_open_tag = Off
